version: '3.9'

services:
  db:
    image: postgres:15
    container_name: user_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build: .
    container_name: user_service
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/userdb
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  pgdata:
